import{S as c,i as a}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();const u=document.querySelector(".gallery");function f({webformatURL:r,largeImageURL:o,tags:l,likes:i,views:e,comments:t,downloads:s}){return`<li class="gallery-item> 
    <figure class="sign">
        <a href="${o}"><img class="list-img" src="${r}" alt="${l}" title="" width="360" height="200"/></a><span class="title-img">
        <figcaption class="title-img"><ul class="figcaption">
      <li class="figcaption-item">Likes<p class="counter">${i}</p></li>
      <li class="figcaption-item">Views<p class="counter">${e}</p></li>
      <li class="figcaption-item">Comments<p class="counter">${t}</p></li>
      <li class="figcaption-item">Downloads<p class="counter">${s}</p></li>
    </ul></figcaption>
    </figure>
   </li>`}function m(r){return r.map(f).join("")}function p(r){const o=m(r);u.innerHTML=o}function d(r){const o=new URLSearchParams({key:"44959261-ea439a2adbf8f7e5770dfe1a3",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:20});fetch(`https://pixabay.com/api/?${o}`).then(i=>{if(!i.ok)throw new Error(i.status);return i.json()}).then(i=>{if(i.total!==0){p(i.hits),new c(".gallery a").refresh();let t=document.getElementById("loader");t.style.display="none"}else a.error({message:"Image is not found",position:"topRight"})}).catch(i=>console.log(i))}const n={btnSubEl:document.querySelector(".btn-search"),formEl:document.querySelector(".form"),input:document.querySelector("input")};n.formEl.addEventListener("submit",r=>{r.preventDefault(),n.input.value.trim()?(d(n.input.value.trim()),n.input.value="",document.body.insertAdjacentHTML("beforeend",'<div id="loader" class="loader" ></div>')):a.error({message:"Please fill in the input field",position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
