import{s as c,i as a}from"./assets/vendor-5c957d73.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const u=document.querySelector(".gallery");function f({webformatURL:r,largeImageURL:o,tags:i,likes:s,views:e,comments:t,downloads:l}){return`<li class="gallery-item> 
    <figure class="sign">
        <a href="${o}"><img class="list-img" src="${r}" alt="${i}" title="" width="360" height="200"/></a><span class="title-img">
        <figcaption class="title-img"><ul class="figcaption">
      <li class="figcaption-item">Likes<p class="counter">${s}</p></li>
      <li class="figcaption-item">Views<p class="counter">${e}</p></li>
      <li class="figcaption-item">Comments<p class="counter">${t}</p></li>
      <li class="figcaption-item">Downloads<p class="counter">${l}</p></li>
    </ul></figcaption>
    </figure>
   </li>`}function m(r){return r.map(f).join("")}function p(r){const o=m(r);u.innerHTML=o}function d(r){document.querySelector(".form").insertAdjacentHTML("afterend",'<div id="loader" class="loader"></div>');const i=new URLSearchParams({key:"44959261-ea439a2adbf8f7e5770dfe1a3",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:20});return fetch(`https://pixabay.com/api/?${i}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}const n={btnSubEl:document.querySelector(".btn-search"),formEl:document.querySelector(".form"),input:document.querySelector("input"),ul:document.querySelector("ul")};n.formEl.addEventListener("submit",r=>{r.preventDefault(),n.ul.innerHTML="",n.input.value.trim()?(d(n.input.value.trim()).then(i=>{i.total!==0?(p(i.hits),new c(".gallery a").refresh()):a.error({message:"Image is not found",position:"topRight"})}).catch(i=>console.log(i)).finally(()=>{document.querySelector(".loader").remove()}),n.input.value=""):a.error({message:"Please fill in the input field",position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
